### PR TITLE
Can view map in SVG (client-side)

### PR DESCRIPTION
**Pull request by ScottWeinstein**

### CODE REVIEW

**Comment by cdaniel** [comment]
Hi Scott,

I am afraid this change cannot be merged. Rendering maps server-side is much more important than rendering them in the client - especially because one of the next features is sharing maps and making them embeddable (twitter, emails, webpages, wikis). They must be served from the server, and I have absolutely no assumptions about the client...

**Comment by cdaniel** [comment]
I have used your code and created https://github.com/cdaniel/wardleymapstool/pull/18, but it is still not complete.

I'll keep that open because you've made a lot of useful improvements - which I will incorporate after basic server-side rendering will be done.

**Comment by ScottWeinstein** [comment]
Agree that we want server side export, But what's the issue w/ merging this in as is?

**Comment by cdaniel** [comment]
I will merge those improvements today. That's what I meant in my previous comment.

There is just a small issue with the 'boolean bug' - at some point in time I've made a terrible mistake of storing those values in the mongo as strings, and as a consequence simple checks like if(var) don't work - 'true' and 'false' are always true. Merging this part will take a bit longer, because I will have to edit a _production_ database and check literally every place where those variables are used.

**Pull request merged**
