### PR TITLE
canvas is optional dependency

### PR DESCRIPTION
**Pull request by ScottWeinstein**
For two reasons

1. canvas can be some work to install, and it's not _critical_ for use of the tool
2. it opens the way for svg export

### CODE REVIEW

**Comment by cdaniel** [comment]
THANK YOU!

**Comment by cdaniel** [comment]
What IDE do you use?

**Comment by ScottWeinstein** [comment]
I use sublime text. You asked b/c of some of the white-space diffs? If you
put in an editorconfig <http://editorconfig.org/> I'll make sure sublime
follows the standards you set.

**Comment by cdaniel** [comment]
I have no standards, I bet you are far better in JS than me :). I use Eclipse, but promise to learn from you as fast as possible ;-).

**Pull request merged**
